# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Laurens van der Maas
title: Data Scientist
email: laurens@vdmaas.nl
website: superlaut.github.io

# Social links
# twitter_username: facespics
github_username:  superlaut
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: laut020
linkedin_username: lautvdmaas
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
about_title: About Me
about_profile_image: images/Portret.JPG
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Laurens. I do this and this.
  
  I am most skilled in: <mark>Python</mark>, <mark>SQL</mark>, and <mark>Spark</mark>.

#Projects Section
projects_title: Projects

#Experience Section
experience_title: Experience

#Education Section
educaton_title: Education

# More Section
more_title: Interests
more_content: | # this will include new lines to allow paragraphs
  Alongside my academic interests I love:
   - Playing the Piano
   - Rock Climbing
   - FIFA on the couch

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
